user:
  length_of_name: 50
  length_of_email: 255
  length_of_password: 6
  gravatar_size: 80
  remember_user: 1
  per_page: 30
gravatar:
  size: 50
  remember_user: 1
micropost:
  leng: 140
  avatar_size: 50
  per_page: 10
image_size: 5
height: 400
width: 400
image_follow_user: 30
